# Use the latest Ubuntu as the base image
FROM ubuntu:latest

# Update package list and upgrade all installed packages
RUN apt-get update && \ apt-get upgrade -y

# When the container starts, print Hello, World!
CMD ["echo", "Hello, World!"]
